### ISSUE TITLE
'SEGTrackPayload.h' file not found

### ISSUE THREAD

**Issue by iMacHumphries** [segment-integrations/analytics-ios-integration-nielsen-dtvr#13]
When using Cocoapods with the `generate_multiple_pod_projects` option I see this error in `SEGNielsenDTVRIntegration.m`:

`'SEGTrackPayload.h' file not found`

To reproduce this issue just create a project with this Podfile:

```
source 'https://cdn.cocoapods.org/'
source 'https://github.com/NielsenDigitalSDK/nielsenappsdk-ios-specs-dynamic.git'

install! 'cocoapods',
  :generate_multiple_pod_projects => true

target 'TestPods' do
  use_frameworks!
  platform :ios, '12.0'
  pod 'Analytics', '4.1.0'
  pod 'NielsenAppSDK', '8.0.0'
  pod 'Segment-Nielsen-DTVR', :git => 'https://github.com/segment-integrations/analytics-ios-integration-nielsen-dtvr.git', :tag => '1.0.0'
end

```

**Comment by kdaswani** [comment]
Resolved in version 1.0.2: https://github.com/segment-integrations/analytics-ios-integration-nielsen-dtvr/blob/master/CHANGELOG.md#version-102-26th-may-2021.
